//modules
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";

//styles
import "./globals.css";

//components
import ContextProvider from "@/components/contextProvider";
import AntdStyledComponentsRegistry from "@/components/antStyled";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "HelloAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <NextTopLoader showSpinner={false} />
        <Toaster
          toastOptions={{
            className: "text-[14px]",
          }}
        />
        <ContextProvider>
          <AntdStyledComponentsRegistry>
            {children}
          </AntdStyledComponentsRegistry>
        </ContextProvider>
      </body>
    </html>
  );
}
